import './globals.css'
import { Inter } from 'next/font/google'
import ProviderRedux  from '../redux/ProviderRedux'
import NarBarComponents from '@/components/NarBarComponents'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CAM GIVING',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderRedux>
          <NarBarComponents/>
          {children}
        </ProviderRedux>
      </body>
    </html>
  )
}
